spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: orders
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: payments
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/payments/**
          - id: stripewebhooks
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/webhook/stripe/**
          - id: currency
            uri: lb://product-service
            predicates:
              - Path=/api/v1/products/**
          - id: inventory
            uri: lb://inventory-service
            predicates:
              - Path=/api/v1/inventory/**

          - id: cart
            uri: lb://cart-service
            predicates:
              - Path=/api/v1/carts/**
          - id: notification
            uri: lb://notification-service
            predicates:
              - Path=/api/v1/notification/**
#          - id: appuser-service
#            uri: lb://ias-user-service
#            predicates:
#              - Path=/api/v1/appuser/**



eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

server:
  port: 8088